import React from "react";
import { Grid, Typography, makeStyles } from "@material-ui/core";
import Card from "@material-ui/core/Card";
import CardActionArea from "@material-ui/core/CardActionArea";
import CardActions from "@material-ui/core/CardActions";
import CardContent from "@material-ui/core/CardContent";
import CardMedia from "@material-ui/core/CardMedia";
import { HashLink } from 'react-router-hash-link';
import { design, panel, inverter, mounting, battery, balance } from "./FileLinks";

const useStyles = makeStyles({
  root: {
    maxWidth: "300px",
    borderRadius: "0px",
    "& .MuiCardContent-root": {
      textAlign: "left",
      padding: "10px",
    },
    "& .MuiCardActions-root": {
      padding: "10px ",
    },
    "& .MuiTypography-body2": {
      lineHeight: 1.3,
    },
    "& .Mui-expanded": {
      backgroundColor: "#ffd54f",
      color: "black",
      margin: "0px",
    },
  },
  media: {
    width: "100%",
    aspectRatio: "1/1",
    objectFit: "cover",
    border: "10px solid black",
  },
  grid: {
    padding: "0 1rem 1rem 1rem",
  },
});

const CardComponents = () => {
  const classes = useStyles();

  return (
    <>
      {/* solar designs */}
      <Grid item xs={12} sm={6} md={4} align="center" className={classes.grid}>
        <Card className={classes.root}>
          <CardActionArea>
            <CardMedia className={classes.media} image={design} title="Contemplative Reptile" />
            <CardContent>
              <Typography gutterBottom variant="h5" component="h2">
                Solar Designs
              </Typography>
              <Typography variant="body2" color="textSecondary" component="p">
                Solar design is the representation of the photovoltaic system characteristics such as civil and
                electrical rendition including panel placement, mounting structure design and dimensions, electrical
                connections and earthing diagram, etc. They also include simulations of the environmental conditions
                faced by a PV system. It is a mandatory requirement for installation of solar power systems as they help
                us minimize error in erecting structures and assembling electrical systems. Please refer to the link
                below for detailed description:
              </Typography>
            </CardContent>
            <CardActions>
              <HashLink to="/design">
                <Typography variant="body1" color="secondary">
                  <strong>Read more</strong>
                </Typography>
              </HashLink>
            </CardActions>
          </CardActionArea>
        </Card>
      </Grid>
      {/* solar panels */}
      <Grid item xs={12} sm={6} md={4} align="center" className={classes.grid}>
        <Card className={classes.root}>
          <CardActionArea>
            <CardMedia className={classes.media} image={panel} title="Contemplative Reptile" />
            <CardContent>
              <Typography gutterBottom variant="h5" component="h2">
                Solar Panels
              </Typography>
              <Typography variant="body2" color="textSecondary" component="p">
                Solar panels collect clean renewable energy in the form of sunlight and convert that light into
                electricity which can then be used to provide power for electrical loads. Solar panels are composed of
                several individual solar cells which are themselves composed of layers of silicon, phosphorus, and
                boron, etc.. The greater the number of solar cells, the more effective the solar panel functionality.
                Multiple panels are connected together to form arrays as per the desired capacity of the system. Please
                refer to the link below for detailed description:
              </Typography>
            </CardContent>
            <CardActions>
              <HashLink to="/solarproducts/#solarpanel">
                <Typography variant="body1" color="secondary">
                  <strong>Read more</strong>
                </Typography>
              </HashLink>
            </CardActions>
          </CardActionArea>
        </Card>
      </Grid>
      {/* solar inverter */}
      <Grid item xs={12} sm={6} md={4} align="center" className={classes.grid}>
        <Card className={classes.root}>
          <CardActionArea>
            <CardMedia className={classes.media} image={inverter} title="Contemplative Reptile" />
            <CardContent>
              <Typography gutterBottom variant="h5" component="h2">
                Solar Inverter
              </Typography>
              <Typography variant="body2" color="textSecondary" component="p">
                Solar inverters are used to convert the direct current (DC) electricity generated by solar photovoltaic
                modules into alternating current (AC) electricity, which is used for local transmission of electricity,
                as well as most appliances in our homes. PV systems either have one inverter that converts the
                electricity generated by all of the modules, or microinverters that are attached to each individual
                module. Solar inverter also synchronizes generated electricity with the grid so that generated power
                from the module can be injected into the grid. Please refer to the link below for detailed description:
              </Typography>
            </CardContent>
            <CardActions>
              <HashLink to="/solarproducts/#solarinverter">
                <Typography variant="body1" color="secondary">
                  <strong>Read more</strong>
                </Typography>
              </HashLink>
            </CardActions>
          </CardActionArea>
        </Card>
      </Grid>
      {/* Solar Batteries */}
      <Grid item xs={12} sm={6} md={4} align="center" className={classes.grid}>
        <Card className={classes.root}>
          <CardActionArea>
            <CardMedia className={classes.media} image={battery} title="Contemplative Reptile" />
            <CardContent>
              <Typography gutterBottom variant="h5" component="h2">
                Solar Batteries
              </Typography>
              <Typography variant="body2" color="textSecondary" component="p">
                Solar batteries are an additional component that allows for the storage of solar photovoltaic energy, so
                we can use it to power our homes at night or when weather elements keep sunlight from reaching PV
                panels. Not only can they be used in homes, but batteries are playing an increasingly important role for
                utilities. As customers feed solar energy back into the grid, batteries can store it so it can be
                returned to customers at a later time. The increased use of batteries will help modernize and stabilize
                our country's electric grid. Please refer to the link below for detailed description:
              </Typography>
            </CardContent>
            <CardActions>
              <HashLink to="/solarproducts/#solarbatteries">
                <Typography variant="body1" color="secondary">
                  <strong>Read more</strong>
                </Typography>
              </HashLink>
            </CardActions>
          </CardActionArea>
        </Card>
      </Grid>
      {/* Module mounting structure */}
      <Grid item xs={12} sm={6} md={4} align="center" className={classes.grid}>
        <Card className={classes.root}>
          <CardActionArea>
            <CardMedia className={classes.media} image={mounting} title="Contemplative Reptile" />
            <CardContent>
              <Typography gutterBottom variant="h5" component="h2">
                Module mounting structure
              </Typography>
              <Typography variant="body2" color="textSecondary" component="p">
                PV arrays must be mounted on a stable, durable structure that can support the array and withstand wind,
                rain, hail, and corrosion over decades. These structures tilt the PV array at a fixed angle determined
                by the local latitude, orientation of the structure, and electrical load requirements. Rack mounting is
                currently the most common method because it is robust, versatile, and easy to construct and install.
                More sophisticated and less expensive methods continue to be developed. Please refer to the link below
                for detailed description:
              </Typography>
            </CardContent>
            <CardActions>
              <HashLink to="/solarproducts/#modulemounting">
                <Typography variant="body1" color="secondary">
                  <strong>Read more</strong>
                </Typography>
              </HashLink>
            </CardActions>
          </CardActionArea>
        </Card>
      </Grid>
      {/* Balance of System  */}
      <Grid item xs={12} sm={6} md={4} align="center" className={classes.grid}>
        <Card className={classes.root}>
          <CardActionArea>
            <CardMedia className={classes.media} image={balance} title="Contemplative Reptile" />
            <CardContent>
              <Typography gutterBottom variant="h5" component="h2">
                Balance of System
              </Typography>
              <Typography variant="body2" color="textSecondary" component="p">
                The balance of system (BOS) refers to the components and equipment that move DC energy produced by solar
                panels through the conversion system which in turn produces AC electricity. A BOS encompasses all
                components of a photovoltaic system other than the photovoltaic panels, solar inverters, batteries and
                mounting structures. This includes wiring, switchboards, junction boxes, earthing system, lightning
                protection system, battery charger, etc.. Please refer to the link below for detailed description:
              </Typography>
            </CardContent>
            <CardActions>
              <HashLink to="/solarproducts/#balancesystem">
                <Typography variant="body1" color="secondary">
                  <strong>Read more</strong>
                </Typography>
              </HashLink>
            </CardActions>
          </CardActionArea>
        </Card>
      </Grid>
    </>
  );
};

export default CardComponents;
