import React from "react";
import { Grid, Typography, makeStyles, useMediaQuery } from "@material-ui/core";
import CrucialSteps from "./CrucialSteps";
import InstallationSteps from "./InstallationSteps";
import Cards from "./Cards";
import { ongrid, offgrid, hybrid, maintainence, tag1, tag5 } from "./FileLinks";

const useStyles = makeStyles((theme) => ({
  container: {
    backgroundColor: "#bfbfbf",
    padding: "0 0 0 2.5rem",
    margin: "0px",
    "& .MuiTypography-body1": {
      lineHeight: 1.3,
    },
    "& .MuiTypography-h6": {
      lineHeight: 1.2,
    },
    "& .MuiTypography-root": {
      textAlign: "justify",
    },
    [theme.breakpoints.down("xs")]: {
      padding: "0",
    },
  },
  grid: {
    backgroundColor: "#fafafa",
    padding: "3rem",
    [theme.breakpoints.down("xs")]: {
      padding: "1.5rem",
    },
  },
  systemImg: {
    display: "flex",
    margin: "0 auto",
    border: "5px solid #ffd05b",
    borderRadius: "10px",
  },
}));

const SolarInstallation = () => {
  const classes = useStyles();
  const matches = useMediaQuery("(min-width:600px)");

  return (
    <div className={classes.container}>
      <Grid container>
        {/* Solar Installation */}
        <Grid className={classes.grid} item xs={12} style={{ paddingTop: "0rem", paddingBottom: "0rem" }}>
          <div style={{ maxWidth: "100%" }}>
            <img src={tag1} style={{ display: "flex", width: "100%" }} alt="Installation" />
          </div>
        </Grid>
        <Grid className={classes.grid} item xs={12}>
          <div>
            <Typography variant={matches ? "h3" : "h4"} color="secondary" gutterBottom>
              <strong>SOLAR INSTALLATION</strong>
            </Typography>
            <Typography variant="body1" color="secondary">
              The amount of sunlight that strikes the earth’s surface in an hour and a half is enough to handle the
              entire world’s energy consumption for a full year. Solar energy is the cleanest and most abundant
              renewable energy source available. Solar power is energy from the sun that is converted into thermal or
              electrical energy. Solar technologies can harness this energy for a variety of uses, including generating
              electricity, providing light or a comfortable interior environment, and heating water for domestic,
              commercial, or industrial use. There are three main ways to harness solar energy: photovoltaics, solar
              heating & cooling, and concentrating solar power. Photovoltaics generate electricity directly from
              sunlight via an electronic process and can be used to power anything from small electronics such as
              calculators and road signs up to homes and large commercial businesses. Solar heating & cooling (SHC) and
              concentrating solar power (CSP) applications both use the heat generated by the sun to provide space or
              water heating in the case of SHC systems, or to run traditional electricity-generating turbines in the
              case of CSP power plants.
            </Typography>
            <br />
            <Typography variant="body1" color="secondary">
              Let us focus on the scope of generating electricity from sunlight from photovoltaic (PV) technology. PV
              materials and devices convert sunlight into electrical energy. A single PV device is known as a cell. An
              individual PV cell is usually small, typically producing about 1 or 2 watts of power. These cells are made
              of different semiconductor materials and are often less than the thickness of four human hairs. In order
              to withstand the outdoors for many years, cells are sandwiched between protective materials in a
              combination of glass and/or plastics.
            </Typography>
            <br />
            <Typography variant="body1" color="secondary">
              To boost the power output of PV cells, they are connected together in chains to form larger units known as
              modules or panels. Modules can be used individually, or several can be connected to form arrays. One or
              more arrays is then connected to the electrical grid as part of a complete PV system. Because of this
              modular structure, PV systems can be built to meet almost any electric power need, small or large.
            </Typography>
            <br />
            <Typography variant="body1" color="secondary">
              PV modules and arrays are just one part of a PV system. Systems also include mounting structures that
              point panels toward the sun, along with the components that take the direct-current (DC) electricity
              produced by modules and convert it to the alternating-current (AC) electricity used to power all of the
              appliances in your home.
            </Typography>
          </div>
        </Grid>
        {/* yellow box */}
        <Grid item xs={12} style={{ backgroundColor: "#ffd05b", height: "2.5rem" }}></Grid>
        {/* types of PV systems */}
        <Grid className={classes.grid} item container xs={12}>
          <Grid item xs={12}>
            <Typography variant={matches ? "h4" : "h5"} color="secondary">
              <strong>There are three types of PV systems</strong>
            </Typography>
            <Typography variant={matches ? "h4" : "h5"} color="secondary">
              <strong>(Solar power systems):</strong>
            </Typography>
          </Grid>
          {/* Ongrid */}
          <Grid item container xs={12}>
            <Grid item xs={12} md={7}>
              <Typography variant="h5" color="secondary" style={{ margin: "40px 0" }}>
                <strong>On-Grid Solar Power system:</strong>
              </Typography>
              <Typography variant="body1" color="secondary">
                On-grid or grid-tie solar systems are by far the most common and widely used by homes and businesses.
                These systems do not need batteries and use either solar inverters or micro inverters and are connected
                to the public electricity grid. Any excess solar power that you generate is exported to the electricity
                grid and you usually get paid a feed-in-tariff (FiT) or credits for the energy you export.
              </Typography>
              <br />
              <Typography variant="body1" color="secondary">
                In an on-grid system, this is what happens after electricity reaches the switchboard:
              </Typography>
            </Grid>
            <Grid item xs={12} md={5} style={{ padding: matches ? "2rem" : "2rem 0" }}>
              <div style={{ maxWidth: "300px", margin: "0 auto" }}>
                <img
                  className={classes.systemImg}
                  style={{ width: "100%", aspectRatio: "1/1" }}
                  src={ongrid}
                  alt="On Grid"
                />
              </div>
            </Grid>
          </Grid>
          <Grid item container xs={12}>
            <Grid item xs={12} md={4} style={{ backgroundColor: "black" }}>
              <div style={{ color: "white", padding: matches ? "2rem" : "1rem", borderTop: "5px solid #fafafa" }}>
                <Typography variant="h5">
                  <strong>METERING SYSTEMS</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  They work differently in many states and countries around the world. In this description, it is
                  assumed that the meter is only measuring the electricity being exported to the grid, as is the case in
                  most of India. In some states, meters measure all solar electricity produced by your system, and
                  therefore your electricity will run through your meter before reaching the switchboard and not after
                  it.
                </Typography>
                <br />
                <Typography variant="body1">
                  In some countries (currently in U.S.A), the meter measures both production and export, and the
                  consumer is charged (or credited) for net electricity used over a month or year period.
                </Typography>
              </div>
            </Grid>
            <Grid item xs={12} md={4} style={{ backgroundColor: "#ffd05b" }}>
              <div
                style={{
                  backgroundColor: "black",
                  color: "white",
                  padding: matches ? "2rem" : "1rem",
                  border: "5px solid #fafafa",
                  borderBottom: "none",
                }}
              >
                <Typography variant="h5">
                  <strong>THE METER</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  Excess solar energy runs through the meter, which calculates how much power you are either exporting
                  or importing (purchasing).
                </Typography>
                <br />
                <br />
              </div>
            </Grid>
            <Grid item xs={12} md={4} style={{ backgroundColor: "black" }}>
              <div style={{ color: "white", padding: matches ? "2rem" : "1rem", borderTop: "5px solid #fafafa" }}>
                <Typography variant="h5">
                  <strong>THE ELECTRICITY GRID</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  Electricity that is sent to the grid from your solar system can then be used by other consumers on the
                  grid (your neighbours). When your solar system is not operating, or you are using more electricity
                  than your system is producing, you will start importing or consuming electricity from the grid
                </Typography>
                <br />
                <Typography variant="body1">
                  Unlike hybrid systems, on-grid solar systems are not able to function or generate electricity during a
                  blackout due to safety reasons. Since blackouts usually occur when the electricity grid is damaged; If
                  the solar inverter was still feeding electricity into a damaged grid it would risk the safety of the
                  people repairing the fault/s in the network.
                </Typography>
              </div>
            </Grid>
          </Grid>
          {/* off grid */}
          <Grid item container xs={12} style={{ margin: "3rem 0 1rem 0" }}>
            <Grid item xs={12} md={7}>
              <Typography variant="h5" color="secondary" style={{ marginBottom: "40px" }}>
                <strong>Off-Grid Systems:</strong>
              </Typography>
              <Typography variant="body1" color="secondary">
                An off-grid system is not connected to the electricity grid and therefore requires battery storage.
                Off-grid solar systems must be designed appropriately so that they will generate enough power throughout
                the year and have enough battery capacity to meet the home’s requirements, even in the depths of winter
                when there is generally much less sunlight. The high cost of batteries and off-grid inverters means
                off-grid systems are much more expensive than on-grid systems and so are usually only needed in more
                remote areas that are far from the electricity grid. However battery costs are reducing rapidly, so
                there is now a growing market for off-grid solar battery systems even in cities and towns.
              </Typography>
              <br />
              <Typography variant="body1" color="secondary">
                In residential and commercial off-grid systems, DC coupled systems are used where a solar charge
                controller is used to manage the battery charging, then the DC power is converted to AC using an
                off-grid inverter and sent to your home appliances. The main components of an off-grid system is given
                below:
              </Typography>
            </Grid>
            <Grid item xs={12} md={5} style={{ padding: matches ? "2rem" : "2rem 0" }}>
              <div style={{ maxWidth: "300px", margin: "0 auto" }}>
                <img
                  className={classes.systemImg}
                  style={{ width: "100%", aspectRatio: "1/1" }}
                  src={offgrid}
                  alt="off Grid"
                />
              </div>
            </Grid>
          </Grid>
          <Grid item container xs={12}>
            <Grid item xs={12} md={6} style={{ backgroundColor: "black" }}>
              <div
                style={{
                  color: "white",
                  padding: matches ? "2rem" : "1rem",
                  borderRight: "10px solid #ffd05b",
                  height: "100%",
                }}
              >
                <Typography variant="h5">
                  <strong>THE BATTERY BANK</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  In an off-grid system there is no public electricity grid. Once solar power is used by the appliances
                  in your property, any excess power will be sent to your battery bank. Once the battery is full it will
                  stop receiving power from the solar system. When your solar system is not working (night time or
                  cloudy days), your appliances will draw power from the batteries.
                </Typography>
              </div>
            </Grid>

            <Grid item xs={12} md={6} style={{ backgroundColor: "black" }}>
              <div
                style={{
                  color: "white",
                  padding: matches ? "2rem" : "1rem",
                  borderLeft: "10px solid #ffd05b",
                  height: "100%",
                }}
              >
                <Typography variant="h5">
                  <strong>BACKUP GENERATOR</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  For times of the year when the batteries are low on charge and the weather is very cloudy you will
                  generally need a backup power source, such as a backup generator. The size of the backup generator
                  (measured in kVA) should be adequate to supply your house and charge the batteries at the same time.
                </Typography>
              </div>
            </Grid>
          </Grid>
          {/* hybrid */}
          <Grid item container xs={12} style={{ margin: "3rem 0 1rem 0" }}>
            <Grid item xs={12} md={7}>
              <Typography variant="h5" color="secondary" style={{ marginBottom: "40px" }}>
                <strong>Hybrid Systems:</strong>
              </Typography>
              <Typography variant="body1" color="secondary">
                Modern hybrid systems combine grid connection and battery storage in one and are now available in many
                different forms and configurations. Due to the decreasing cost of battery storage, systems that are
                already connected to the electricity grid can start taking advantage of battery storage as well. This
                means being able to store solar energy that is generated during the day and using it at night. When the
                stored energy is depleted, the grid is there as a back up, allowing consumers to have the best of both
                worlds. Hybrid systems are also able to charge the batteries using cheap off-peak electricity (usually
                after midnight to 6am). Most hybrid solar systems with battery storage are able to automatically isolate
                from the grid (known as islanding) and continue to supply some power during a blackout.
              </Typography>
              <br />
              <Typography variant="body1" color="secondary">
                The major components of a hybrid system are given below:
              </Typography>
            </Grid>
            <Grid item xs={12} md={5} style={{ padding: matches ? "2rem" : "2rem 0" }}>
              <div style={{ maxWidth: "300px", margin: "0 auto" }}>
                <img
                  className={classes.systemImg}
                  style={{ width: "100%", aspectRatio: "1/1" }}
                  src={hybrid}
                  alt="hybrid"
                />
              </div>
            </Grid>
          </Grid>
          <Grid item container xs={12}>
            <Grid item xs={12} md={6} style={{ backgroundColor: "black" }}>
              <div
                style={{
                  color: "white",
                  padding: matches ? "2rem" : "1rem",
                  borderRight: "10px solid #ffd05b",
                  height: "100%",
                }}
              >
                <Typography variant="h5">
                  <strong>THE BATTERY BANK</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  In a hybrid system once the solar power is used by the appliances in your property, any excess power
                  will be sent to the battery bank. Once the battery bank is fully charged, it will stop receiving power
                  from the solar system. The energy from the battery can then be discharged and used to power your home,
                  usually during the peak evening period when the cost of electricity is typically at its highest.
                </Typography>
              </div>
            </Grid>
            <Grid item xs={12} md={6} style={{ backgroundColor: "black" }}>
              <div
                style={{
                  color: "white",
                  padding: matches ? "2rem" : "1rem",
                  borderLeft: "10px solid #ffd05b",
                  height: "100%",
                }}
              >
                <Typography variant="h5">
                  <strong>THE METER AND ELECTRICITY GRID</strong>
                </Typography>
                <br />
                <Typography variant="body1">
                  Depending on how your hybrid system is set up and whether your utility allows it, once your batteries
                  are fully charged excess solar power not required by your appliances can be exported to the grid via
                  your meter. When your solar system is not in use, and if you have drained the usable power in your
                  batteries your appliances will then start drawing power from the grid.
                </Typography>
              </div>
            </Grid>
          </Grid>
        </Grid>
        {/* yellow box */}
        <Grid item xs={12} style={{ backgroundColor: "#ffd05b", height: "2.5rem" }}></Grid>
        {/* Steps before solar installation */}
        <Grid item container xs={12}>
          <Grid className={classes.grid} style={{ backgroundColor: "white" }} item xs={12} md={6}>
            <Typography variant={matches ? "h4" : "h5"} color="secondary">
              <strong>What Steps do I Need to Take Before Solar power system Installation?</strong>
            </Typography>
            <br />
            <br />
            <Typography variant="h6" color="secondary">
              Here are some crucial steps you need to take before the photovoltaic installation process begins.
            </Typography>
          </Grid>
          <Grid item xs={12} md={6}>
            <div>
              <img src={tag5} style={{ height: "100%", width: "100%", objectFit: "cover" }} alt="" />
            </div>
          </Grid>
          <Grid item xs={12} style={{ backgroundColor: "#fafafa" }}>
            <CrucialSteps />
          </Grid>
        </Grid>
        {/* yellow box */}
        <Grid item xs={12} style={{ backgroundColor: "#ffd05b", height: "2.5rem" }}></Grid>
        {/* installation process */}
        <Grid item container xs={12}>
          <Grid className={classes.grid} item xs={12}>
            <Typography variant={matches ? "h4" : "h5"} color="secondary">
              <strong>Solar Installation process</strong>
            </Typography>
            <br />
            <Typography variant="h6" style={{ lineHeight: 1.3 }} color="secondary">
              Here we will discuss the process of installing a photovoltaic system.The most common location for the
              installation of solar PV panels is the roof. Most roofs typically have the desired specifications for the
              installation, so that panels get the maximum sunlight. Nevertheless, if installation on the roof is not
              applicable or desired, the solar panels could also be mounted on the ground. You just need to make sure
              that there are no objects blocking access to the sun.
            </Typography>
          </Grid>
          <Grid item xs={12} style={{ backgroundColor: "#fafafa" }}>
            <InstallationSteps />
          </Grid>
        </Grid>
        {/* Video */}
        <Grid item xs={12} style={{ backgroundColor: "#fafafa", padding: "3rem 0" }} align="center">
          <Typography variant="h6" color="secondary" style={{ textAlign: "center", margin: "0 1rem" }}>
            <strong>Here is a small video to show the process of solar installation.</strong>
          </Typography>
          <br />
          <br />
          <Grid item container xs={12} alignItems="center">
            <Grid item xs={false} sm={2}>
              <div style={{ backgroundColor: "#ffd05b", height: "2.5rem" }}></div>
            </Grid>
            <Grid item xs={12} sm={8} align="center" alignItems="center">
              <iframe
                style={{ border: "10px solid #ffd05b", aspectRatio: "16/9" }}
                width="100%"
                src="https://www.youtube.com/embed/jSa1tvrrFZg"
                title="YouTube video player"
                frameborder="0"
                allow="encrypted-media; picture-in-picture; fullscreen;"
              ></iframe>
            </Grid>
            <Grid item xs={false} sm={2}>
              <div style={{ backgroundColor: "#ffd05b", height: "2.5rem" }}></div>
            </Grid>
          </Grid>
        </Grid>
        {/* components of solar system */}
        <Grid item xs={12} style={{ backgroundColor: "#bfbfbf", padding: "1rem" }}>
          <Typography variant={matches ? "h4" : "h5"} color="secondary">
            The Components of the rooftop solar system:
          </Typography>
        </Grid>
        <Grid item container xs={12} style={{ backgroundColor: "#fafafa", paddingTop: "2rem" }}>
          <Cards />
        </Grid>
        {/* yellow box */}
        <Grid item xs={12} style={{ backgroundColor: "#ffd05b", height: "2.5rem" }}></Grid>
        {/* panel maintainence */}
        <Grid item container xs={12} className={classes.grid}>
          <Grid item xs={12}>
            <Typography variant={matches ? "h4" : "h5"} color="secondary">
              <strong>Solar Panel Maintenance</strong>
            </Typography>
            <br />
            <Typography variant="body1" color="secondary">
              Since there are no moving parts, solar panels require very little maintenance. Once you have covered the
              installation cost of solar panels, there are not many costs associated with maintaining them. Having said
              that, you should inspect them a few times per year for dirt or some other things that might have piled on
              top. It is important that the panels are clean and there is nothing blocking them from efficiently
              absorbing the sun. Before cleaning the panels yourself, you should consult with your installer about the
              warranty conditions. Some solar panel manufacturers could terminate the warranty if any self cleaning is
              done.
            </Typography>
            <br />
            <Typography variant="body1" color="secondary">
              For a general cleaning, you can just use a normal garden hose to wash the face of the panels. You should
              do this in the morning or evening. Also avoid spraying them with cold water while they are hot because
              that might damage them. Moreover, If the panels need some more cleaning that the hose cannot provide, you
              can use a sponge with soapy water to scrub them. You can also get the services of a cleaning company if
              the panels are too high or need more thorough cleaning. You should have your system examined every 4-6
              years by an installer just to check if there are any malfunctions you need to fix, or something similar..
              It is also a good idea to ask your installer about specific maintenance requirements for your solar
              system.
            </Typography>
          </Grid>
        </Grid>
        <Grid item xs={12}>
          <div style={{ height: "100%", display: "flex", alignItems: "center" }}>
            <img
              style={{
                height: matches ? "450px" : "300px",
                width: "100%",
                display: "flex",
                objectFit: "cover",
              }}
              src={maintainence}
              alt="On Grid"
            />
          </div>
        </Grid>
      </Grid>
    </div>
  );
};

export default SolarInstallation;
