import React, { useState } from "react";
import { Grid, Typography, makeStyles, Link, IconButton, useMediaQuery } from "@material-ui/core";
import PictureAsPdfIcon from "@material-ui/icons/PictureAsPdf";
import { pdfFilesLink, coverImage } from "./FileLinks";
import Table from "@material-ui/core/Table";
import TableBody from "@material-ui/core/TableBody";
import TableCell from "@material-ui/core/TableCell";
import TableContainer from "@material-ui/core/TableContainer";
import TableHead from "@material-ui/core/TableHead";
import TableRow from "@material-ui/core/TableRow";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import ListItemText from "@material-ui/core/ListItemText";
import CheckBoxIcon from "@material-ui/icons/CheckBox";
import HaryanaTable from "./HaryanaTable";

const useStyles = makeStyles((theme) => ({
  root: {
    padding: "3rem",
    [theme.breakpoints.down("xs")]: {
      padding: "1rem",
    },
  },
  iconButton: {
    padding: "0px",
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
  requiredList: {
    "& .MuiListItem-root": {
      padding: "0px",
    },
  },
  outerDiv: {
    borderRadius: "20px",
    borderBottomRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    [theme.breakpoints.down("xs")]: {
      borderRadius: "10px",
      borderBottomRightRadius: "0px",
      borderBottomLeftRadius: "0px",
    },
  },
  innerDiv: {
    padding: "1.5rem",
    border: "10px solid #ffd05b",
    borderRadius: "20px",
    [theme.breakpoints.down("xs")]: {
      padding: "1rem 0",
      border: "5px solid #ffd05b",
      borderRadius: "10px",
    },
    "& .MuiTypography-root": {
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
      WebkitUserSelect: "none",
      WebkitTouchCallout: "none",
      mozUserSelect: "none",
      msUserSelect: "none",
      userSelect: "none",
    },
  },
  outerContent: {
    backgroundColor: "#ffd05b",
    borderBottomLeftRadius: "20px",
    borderBottomRightRadius: "20px",
  },
  innerContent: {
    margin: "20px 0",
    "& div": {
      padding: "1.5rem",
      backgroundColor: "#fafafa",
      borderRadius: "20px",
      [theme.breakpoints.down("xs")]: {
        padding: "1rem",
        borderRadius: "10px",
      },
    },
  },
  cover: {
    minHeight: "400px",
    backgroundImage: `url(${coverImage})`,
    backgroundSize: "100% 100%",
    backgroundPosition: "top center",
    backgroundRepeat: "no-repeat",
    imageRendering: "crisp-edges",
  },
  container: {
    maxHeight: 450,
    "& .MuiTableCell-root": {
      padding: "12px",
    },
    "& .MuiTypography-body1": {
      lineHeight: 1.2,
    },
    "& .MuiTableHead-root .MuiTableCell-root": {
      background: "#e9e9e9",
    },
  },
}));

const Haryana = () => {
  const classes = useStyles();
  const matches = useMediaQuery("(min-width:600px)");
  const [view, setView] = useState(true);

  return (
    <div>
      <Grid container>
        <Grid item container>
          <Grid item xs={12} md={6}>
            <div className={classes.root}>
              <Typography color="secondary" variant={matches ? "h3" : "h4"}>
                <strong>HARYANA</strong>
              </Typography>
              <br />
              <Typography color="secondary" variant="body1" align="justify">
              Haryana is an agrarian state with several geographical constraints such as high cost and paucity of barren land within its borders, with low potential for wind or hydropower. The state has shifted focus mainly on rooftop solar projects and small-scale distributed solar systems besides exploring the potential of megawatt-scale solar projects and parks.
              </Typography>
              <br />
              <Typography color="secondary" variant="body1" align="justify">
              Haryana Power Generation Corporation Limited (HPGCL) is developing 77 MW solar power plants on HPGCL land and 16 MW on land owned by village councils (panchayats). The last budget had announced a scheme to install 50,000 off-grid solar pumps of 3 HP to 10 HP capacity in the State, with installation of 15,000 pumps and 35,000 pumps in two phases. The State government under the Pradhan Mantri Kisan Urja Surksha Evam Utthan Mahabhiyaan (PM-KUSUM) Scheme is providing 75% subsidy, of which 30% subsidy is provided under PM-KUSUM and 45% from the state. The state of Haryana has set a target of 3200 MW of solar power to be generated by the year 2021-22.  The current installed and commissioned solar capacity of the state is 73.27 MW.,{" "}
              </Typography>
            </div>
          </Grid>
          <Grid className={classes.cover} item xs={12} md={6}></Grid>
        </Grid>
        <Grid item xs={12}>
          <div style={{ height: "5rem", backgroundColor: "#ffd05b" }}></div>
        </Grid>
        <Grid item container style={{ backgroundColor: "#e9e9e9" }}>
          {/* The parties eligible */}
          <Grid item xs={12} md={6}>
            <div className={classes.root}>
              <Typography color="secondary" variant={matches ? "h5" : "h6"}>
                <strong>THE PARTIES ELIGIBLE FOR NET METERING POLICY IN HARYANA ARE:</strong>
              </Typography>
              <br />
              <br />
              <Typography color="secondary" variant="body1" align="justify">
              The eligible consumer may install the rooftop solar system under net metering arrangement which:
              </Typography><br/>
              <Typography color="secondary" variant="body1" align="justify">
                <ol type="a">
                <li>
                Shall be within the permissible rated capacity as defined under these Regulations;
                </li>
                <li>
                Shall be located in the consumer premises; 
                </li>
                <li>
                Shall interconnect and operate safely in parallel with the distribution licensee’s network.
                </li>
                </ol>
              </Typography>
            </div>
          </Grid>
          {/* The Eligible Consumer */}
          <Grid item xs={12} md={6}>
            <div style={{ padding: matches ? "1rem" : "0.5rem", border: "1px solid #bfbfbf" }}>
              <div style={{ padding: matches ? "2rem" : "0.5rem", backgroundColor: "#FAFAFA" }}>
                <Typography color="secondary" variant={matches ? "h5" : "h6"}>
                  <strong>
                    THE ELIGIBLE CONSUMER MAY INSTALL THE ROOFTOP SOLAR PV SYSTEM UNDER NET METERING ARRANGEMENT WHICH,
                  </strong>
                </Typography>
                <br />
                <br/>
                <Typography color="secondary" variant="body1" align="justify">
                  <li>
                  Consumers across all categories including residential, commercial and industrial are now allowed to set-up solar projects with a maximum capacity of 2 MW. However, this comes with the condition that solar projects within the range of 1 to 2 MW must have 25% battery storage that should be able to store and deliver energy for 2 hours. 
                  </li>
                  <br />
                  <li>
                  The distribution capacity of transformers has been increased from 30% and 15% to 50% and 30% for LT and HT consumers respectively.
                  </li>
                  <br />
                  <li>
                  The DISCOMs will continue to provide net-metering arrangements to eligible consumers on a non-discriminatory and first-come-first-serve basis, as long as the total capacity of rooftop solar systems does not exceed 500 MW, up from the figure of 200 MW.
                  </li>
                  <br/>
                  <li>
                  Rooftop solar systems commissioned under these regulations, whether self-owned or third-party owned, will be exempted from all wheeling, cross-subsidy, transmission, distribution, and banking charges and surcharges.
                  </li>
                </Typography>

              </div>
            </div>
          </Grid>
        </Grid>
        {/* Table */}
        <Grid item xs={12}>
          <div className={classes.root}>
            <Typography color="secondary" variant={matches ? "h4" : "h5"}>
              <strong>TABLE</strong>
            </Typography>
            <br />
            <Typography variant={matches ? "h5" : "h6"}>
              Application for Net-Metering approval for Photovoltaic system installation:
            </Typography>
            <br />
            <HaryanaTable />
          </div>
        </Grid>
        {/* list of documents */}
        <Grid item xs={12}>
          <div className={classes.root} style={{ backgroundColor: "#e9e9e9" }}>
            <Typography color="secondary" variant={matches ? "h4" : "h5"} gutterBottom>
              <strong>LIST OF DOCUMENTS REQUIRED</strong>
            </Typography>
            <div className={classes.requiredList}>
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Identity Proof (both)
                  </Typography>
                </ListItemText>
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  	PAN Card
                  </Typography>
                </ListItemText>
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Aadhar Card
                  </Typography>
                </ListItemText>
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Residence/ Address Proof
                  </Typography>
                </ListItemText>
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Site Address Proof
                  </Typography>
                </ListItemText>
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Aadhar card and any other document if address differ from Aadhar card
                  </Typography>
                </ListItemText>
              </ListItem> 
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Electricity Bill
                  </Typography>
                </ListItemText>
              </ListItem> 
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  Photograph of site
                  </Typography>
                </ListItemText>
              </ListItem> 
              <ListItem>
                <ListItemIcon>
                  <CheckBoxIcon />
                </ListItemIcon>
                <ListItemText>
                  <Typography variant={matches ? "h5" : "h6"} color="secondary">
                  For other than domestic sector: Registration Certificate, Proof of being institute/ social organization
                  </Typography>
                </ListItemText>
              </ListItem> 

            </div>
            <br />
            <br />

            <div
              className={classes.root}
              style={{ backgroundColor: "#fafafa", borderRadius: matches ? "20px" : "10px" }}
            >
              <Typography color="secondary" variant={matches ? "h5" : "h6"} gutterBottom>
                <strong>Solar Subsidy:</strong>
              </Typography>
              <Typography style={{ lineHeight: 1.2 }} color="secondary" align="justify" variant={matches ? "h6" : "body1"}>
              The Government is providing Financial Assistance for the installation of Grid Connected Rooftop Solar Power Plants at rate of 30% of the cost/ benchmark cost (including the Central Financial Assistance (CFA) of MNRE, if available) or Rs. 20000/- per kWp, whichever is less, for installation of the grid connected rooftop solar power plant ranging from 1 KWp to 500 KWp to the eligible categories. The bench mark cost shall be taken as the cost of the system finalized for installation of the grid connected rooftop SPV power plants for government sector buildings.
              </Typography>
              <br/>
              <Typography color="secondary" align="justify" variant={matches ? "h5" : "body1"} >
              Statistical estimations for installation of Solar PV Power Plant (without battery bank):
              </Typography ><br/>

              <TableContainer className={classes.container}>
              <Table>
            <TableHead>
              <TableRow>
                <TableCell>
                  <Typography variant={matches ? "h6" : "body1"} color="secondary">
                  Capacity
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant={matches ? "h6" : "body1"} color="secondary">
                  1 KWP
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant={matches ? "h6" : "body1"} color="secondary">
                  100 KWP
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant={matches ? "h6" : "body1"} color="secondary">
                  500 KWP
                  </Typography>
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>

                <TableRow hover>
                  <TableCell>
                  Approximate Cost of System (Rs.)
                  </TableCell>
                  <TableCell>
                  49500
                  </TableCell>
                  <TableCell>
                  4170000
                  </TableCell>
                  <TableCell>
                  20125000
                  </TableCell>
                </TableRow>

                <TableRow hover>
                  <TableCell>
                  Financial Assistance
                  </TableCell>
                  <TableCell>
                  14850 
                  </TableCell>
                  <TableCell>
                  1251000 
                  </TableCell>
                  <TableCell>
                  6037500 
                  </TableCell>
                </TableRow>

                <TableRow hover>
                  <TableCell>
                  Approximate User Cost (Rs.)
                  </TableCell>
                  <TableCell>
                  34650 
                  </TableCell>
                  <TableCell>
                  2919000 
                  </TableCell>
                  <TableCell>
                  14087500 
                  </TableCell>
                </TableRow>

                <TableRow hover>
                  <TableCell>
                  Life (yrs.)
                  </TableCell>
                  <TableCell>
                  25 
                  </TableCell>
                  <TableCell>
                  25 
                  </TableCell>
                  <TableCell>
                  25 
                  </TableCell>
                </TableRow>

                <TableRow hover>
                  <TableCell>
                  Electricity Generation (KWh)
                  </TableCell>
                  <TableCell>
                  1500
                  </TableCell>
                  <TableCell>
                  150000 
                  </TableCell>
                  <TableCell>
                  750000 
                  </TableCell>
                </TableRow>

                <TableRow hover>
                  <TableCell>
                  Approximate annual saving on energy (Rs.) (Tariff taken as Rs. 7.5 per unit)
                  </TableCell>
                  <TableCell>
                  11250
                  </TableCell>
                  <TableCell>
                  11125000 
                  </TableCell>
                  <TableCell>
                  5625000 
                  </TableCell>
                </TableRow>

                <TableRow hover>
                  <TableCell>
                  Payback period (Yrs.)*
                  </TableCell>
                  <TableCell>
                  3.08
                  </TableCell>
                  <TableCell>
                  2.6 
                  </TableCell>
                  <TableCell>
                  2.5 
                  </TableCell>
                </TableRow>
                </TableBody>
              </Table>
              </TableContainer>
              <Typography color="secondary" variant="body2" align="justify">
              *Payback period has been calculated assuming availability of subsidy.
              </Typography>
              
            </div>
          </div>
        </Grid>
        {/* Residential & Commericial */}
        <Grid item xs={12} style={{ padding: matches ? "100px 20px" : "50px 10px" }}>
          <Grid item container justify="center">
            <Grid item xs={6}>
              <div
                className={classes.outerDiv}
                style={{
                  padding: matches ? "0px 10px 10px 0px" : "0px 5px 5px 0px",
                  backgroundColor: view ? "#ffd05b" : "#fafafa",
                }}
              >
                <div
                  className={classes.innerDiv}
                  style={{
                    backgroundColor: view ? "#ffd05b" : "#fafafa",
                  }}
                >
                  <Typography
                    variant={matches ? "h4" : "h6"}
                    align="center"
                    onClick={() => setView(true)}
                    style={{ color: view ? "white" : "#ffd05b" }}
                  >
                    <strong>RESIDENTIAL</strong>
                  </Typography>
                </div>
              </div>
            </Grid>
            <Grid item xs={6}>
              <div
                className={classes.outerDiv}
                style={{
                  padding: matches ? "0px 0px 10px 10px" : "0px 0px 5px 5px",
                  backgroundColor: !view ? "#ffd05b" : "#fafafa",
                }}
              >
                <div
                  className={classes.innerDiv}
                  style={{
                    backgroundColor: !view ? "#ffd05b" : "#fafafa",
                  }}
                >
                  <Typography
                    variant={matches ? "h4" : "h6"}
                    align="center"
                    onClick={(e) => setView(false)}
                    style={{ color: !view ? "white" : "#ffd05b" }}
                  >
                    <strong>COMMERCIAL</strong>
                  </Typography>
                </div>
              </div>
            </Grid>
          </Grid>
          {/* content */}
          <Grid
            item
            container
            className={classes.outerContent}
            style={{
              borderTopRightRadius: view && (matches ? "20px" : "10px"),
              borderTopLeftRadius: !view && (matches ? "20px" : "10px"),
            }}
          >
            <Grid item xs={12}>
              <div style={{ padding: matches ? "1rem 3rem" : "1rem" }}>
                {view ? (
                  <>
                    {/* Residential */}
                    <div>
                      {/* Capacity */}
                      <div className={classes.innerContent}>
                        <Typography style={{ color: "white" }} variant={matches ? "h4" : "h5"} gutterBottom>
                          CAPACITY OF SOLAR SYSTEM
                        </Typography>
                        <div>
                          <Typography variant={matches ? "h6" : "body1"} color="secondary" align="justify">
                            <li>
                              <strong>Size: </strong>=2 MW
                            </li>
                            <li>
                            From 1 to 2MW, there is a mandate to have 25% battery storage that should be able to store and deliver energy for 2 hours.
                            </li>
                            <li>
                              <strong>Conditions: </strong>=100% of your Sanctioned Load
                            </li>
                            <li>
                            Cumulative capacity of all solar systems installed in your area shall not exceed 50% of Local Distribution transformer capacity in your area.
                            </li>
                            
                          </Typography>
                        </div>
                      </div>
                      {/* ownership */}
                      <div className={classes.innerContent}>
                        <Typography style={{ color: "white" }} variant={matches ? "h4" : "h5"} gutterBottom>
                          OWNERSHIP OPTIONS
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"}>
                            <li>Self ownership (CAPEX model)</li>
                          </Typography>
                        </div>
                      </div>
                      {/* Billing */}
                      <div className={classes.innerContent}>
                        <Typography style={{ color: "white" }} variant={matches ? "h4" : "h5"} gutterBottom>
                          BILLING MECHANISM
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"}>
                            <li>Annual Settlement</li>
                          </Typography>
                        </div>
                      </div>
                      {/* Others */}
                      <div className={classes.innerContent}>
                        <Typography style={{ color: "white" }} variant={matches ? "h4" : "h5"} gutterBottom>
                          OTHERS
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"} align="justify">
                            <li>
                            Mandatory for new residential buildings having plot size more than 500 sq. yards to install 3% to 5% capacity of their Sanctioned Load on solar.
                            </li>
                            <li>
                            No permission is required from the building plan sanctioning authority forsetting up of rooftop solar power plants.
                            </li>
                            <li>Electricity taxes, cess, electricity duty, wheeling charges, cross subsidy charges, transmission and distribution charges: totally waived off for Rooftop Solar Projects.</li>
                          </Typography>
                        </div>
                      </div>
                    </div>
                  </>
                ) : (
                  <>
                    {/* Commercial */}
                    <div>
                      {/* Capacity */}
                      <div className={classes.innerContent}>
                        <Typography gutterBottom style={{ color: "white" }} variant={matches ? "h4" : "h5"}>
                          CAPACITY OF SOLAR SYSTEM
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"} align="justify">
                          <li>
                              <strong>Size: </strong>=2 MW
                            </li>
                            <li>
                            From 1 to 2MW, there is a mandate to have 25% battery storage that should be able to store and deliver energy for 2 hours.
                            </li>
                            <li>
                              <strong>Conditions: </strong>=100% of your Sanctioned Load
                            </li>
                            <li>
                            	Cumulative capacity of all solar systems installed in your area shall not exceed 50% (LT connection) & 30% (HT connection) of Local Distribution transformer capacity in your area.
                            </li>
                           
                          </Typography>
                        </div>
                      </div>
                      {/* ownership */}
                      <div className={classes.innerContent}>
                        <Typography gutterBottom style={{ color: "white" }} variant={matches ? "h4" : "h5"}>
                          OWNERSHIP OPTIONS
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"}>
                            <li>Self ownership (CAPEX model)</li>
                          </Typography>
                        </div>
                      </div>
                      {/* Billing */}
                      <div className={classes.innerContent}>
                        <Typography gutterBottom style={{ color: "white" }} variant={matches ? "h4" : "h5"}>
                          BILLING MECHANISM
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"}>
                            <li>Annual Settlement</li>
                          </Typography>
                        </div>
                      </div>
                      {/* Others */}
                      <div className={classes.innerContent}>
                        <Typography gutterBottom style={{ color: "white" }} variant={matches ? "h4" : "h5"}>
                          OTHERS
                        </Typography>

                        <div>
                          <Typography color="secondary" variant={matches ? "h6" : "body1"} align="justify">
                            <li>
                            Mandatory for all Commercial complexes, Offices, Malls, etc. (existing as well as new buildings) having Connected Load of 50 kW and above to install 3% to 5% capacity of their Connected Load of solar.
                            </li>
                            <li>
                            No permission is required from the building plan sanctioning authority for setting up rooftop solar power plants.
                            </li>
                            <li>Electricity taxes, cess, electricity duty, wheeling charges, cross subsidy charges, transmission and distribution charges: totally waived off for Rooftop Solar Projects.</li>
                          </Typography>
                        </div>
                      </div>
                    </div>
                  </>
                )}
              </div>
            </Grid>
          </Grid>
        </Grid>
        {/* Pdf Downloads */}
        <Grid item xs={12}>
          <div style={{ backgroundColor: "#efefef", padding: matches ? "2rem 3rem" : "1rem" }}>
            <Typography color="secondary" variant={matches ? "h4" : "h5"}>
              <strong>PDF DOWNLOADS</strong>
            </Typography>
          </div>
          <div className={classes.root}>
            {pdfFilesLink.map((pdf, index) => {
              return (
                <React.Fragment key={index}>
                  <Grid item container alignItems="center" style={{ marginBottom: "2rem" }}>
                    <Grid item xs={12} md={10}>
                      <Typography
                        color="secondary"
                        gutterBottom
                        style={{ lineHeight: 1.1 }}
                        variant={matches ? "h5" : "h6"}
                      >
                        {pdf.fileName}
                      </Typography>
                    </Grid>
                    <Grid item xs={12} md={2}>
                      <Link color="secondary" href={pdf.fileUrl} download>
                        <div>
                          <IconButton disableRipple className={classes.iconButton}>
                            <PictureAsPdfIcon style={{ fontSize: matches ? "50px" : "40px" }} />
                            <Typography variant="body1">Download Pdf</Typography>
                          </IconButton>
                        </div>
                      </Link>
                    </Grid>
                  </Grid>
                </React.Fragment>
              );
            })}
          </div>
        </Grid>
      </Grid>
    </div>
  );
};

export default Haryana;
