import React from "react";
import { Grid, Typography, Link, makeStyles, useMediaQuery } from "@material-ui/core";
import { battery, batteryType1, batteryType2, warranty, availability, batteryCompanies } from "./FileLinks";
import OpenInNewIcon from "@material-ui/icons/OpenInNew";
import clsx from "clsx";
import Collapse from "@material-ui/core/Collapse";
import IconButton from "@material-ui/core/IconButton";
import ExpandMoreIcon from "@material-ui/icons/ExpandMore";

const useStyles = makeStyles((theme) => ({
  outer: {
    backgroundColor: "#f3f3f3",
    "& .MuiTypography-root": {
      textAlign: "justify",
    },
    marginBottom: "2rem",
  },
  content: {
    padding: "3rem",
    [theme.breakpoints.down("xs")]: {
      padding: "1.5rem",
    },
  },
  staticCard: {
    width: "100%",
    backgroundColor: "black",
    border: "10px solid white",
    padding: "2rem",
    color: "white",
    position: "relative",
    boxShadow: "0 0 20px -5px #4d4d4d",
  },
  blueStrikeLine: {
    height: "1.7rem",
    backgroundColor: "#678CEB",
    position: "absolute",
    left: "0px",
    right: "0px",
  },
  card: {
    backgroundColor: "#b4b4b4",
    color: "white",
    border: "10px solid white",
    boxShadow: "0 0 10px -5px #4d4d4d",
    padding: "2rem",
  },
  cardButton: {
    backgroundColor: "#678CEB",
    height: "30px",
    width: "80px",
    textAlign: "center",
    border: "5px solid white",
    borderTop: "none",
    borderRadius: "10px",
    borderTopRightRadius: "0px",
    borderTopLeftRadius: "0px",
    margin: "0 auto",
  },
  imageBox: {
    maxWidth: "500px",
    margin: "auto",
  },
  image: {
    display: "flex",
    width: "100%",
    margin: "0 auto",
    aspectRatio: "1/1",
  },
  itemContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "2rem",
  },
  strikeLine: {
    backgroundColor: "#4d4d4d",
    height: "10px",
    width: "100%",
    position: "absolute",
    left: "0px",
    right: "0px",
    top: "50%",
  },
}));

const SolarBatteries = () => {
  const matches = useMediaQuery("(min-width:600px)");
  const classes = useStyles();
  const ToggleCards = {
    lithiumIonBattery: false,
    leadAcidBattery: false,
  };

  const [expanded, setExpanded] = React.useState(ToggleCards);

  const handleExpandClick = (name) => {
    switch (name) {
      case "part1":
        setExpanded({ ...expanded, lithiumIonBattery: !expanded.lithiumIonBattery });
        break;
      case "part2":
        setExpanded({ ...expanded, leadAcidBattery: !expanded.leadAcidBattery });
        break;
      default:
        break;
    }
  };

  return (
    <Grid item container xs={12} className={classes.outer}>
      <Grid item xs={12}>
        <div id='solarbatteries' style={{ width: "100%", padding: "2rem 0" }}>
          <Typography color="secondary" variant={matches ? "h3" : "h4"} style={{ textAlign: "center" }}>
            <strong>SOLAR BATTERIES</strong>
          </Typography>
        </div>
      </Grid>
      <Grid item container xs={12}>
        <Grid item xs={12} md={6} className={classes.itemContainer}>
          <div className={classes.imageBox}>
            <img src={battery} alt="Solar Panel" className={classes.image} />
          </div>
        </Grid>
        <Grid item xs={12} md={6}>
          <div className={classes.content}>
            <Typography variant="h6" component="p">
              Solar battery is a device that reserves energy for later consumption that is charged by a connected solar
              system. The stored electricity is consumed after sundown, during energy demand peaks, or during a power
              outage. During excess solar energy generation, the switchboard directs the power generated by the solar
              panels to the battery – charging it up for later use. As soon as the power outage occurs, the battery
              system’s backup gateway will isolate the home from the grid and activate the battery to immediately
              provide power to the circuits it’s been connected to.
            </Typography>
            <br />
            <Typography variant="h6" component="p">
              Having a solar battery system can help mitigate the amount of electricity one would normally buy during
              demand charge billing or peak hours consumption in accordance with Time-Of-Use (TOU) rates by utilities.
            </Typography>
          </div>
        </Grid>
      </Grid>
      <Grid item xs={12} style={{ backgroundColor: "#ffd05b", padding: matches ? "1rem 3rem" : "1.5rem" }}>
        <Typography variant="h6" color="secondary">
          <strong>Demand charges:</strong> These are additional fees that utilities charge non-residential or commercial
          customers for maintaining constant supply of electricity.
        </Typography>
      </Grid>
      <Grid item xs={12} style={{ height: "3rem" }}></Grid>
      <Grid item xs={12} style={{ backgroundColor: "#ffd05b", padding: matches ? "1rem 3rem" : "1.5rem" }}>
        <Typography variant="h6" color="secondary">
          <strong>Time-Of-Use (TOU):</strong> TOU states that the power drawn from the grid at night is more valuable
          than the extra energy produced during the day leading to higher unit prices of electricity.
        </Typography>
      </Grid>
      {/* --- */}
      <Grid item container xs={12} style={{ padding: matches && "0 3rem", position: "relative", width: "100%" }}>
        {matches && <div className={classes.strikeLine}></div>}
        <Grid item xs={12} style={{ marginTop: "3rem" }}>
          <Typography variant="h6" color="secondary" style={{ textAlign: "center" }}>
            <strong>THE CHARACTERISTICS OF A SOLAR BATTERY STORAGE SYSTEM ARE GIVEN BELOW:</strong>
          </Typography>
        </Grid>
        <Grid item xs={12} md={4} style={{ padding: "2rem" }}>
          <div className={classes.staticCard}>
            <Typography variant="body1" component="p" style={{ textAlign: "center" }}>
              <strong>BATTERY LIFE</strong>
            </Typography>
            <br />
            <Typography variant="body1" component="p">
              A battery’s lifespan is usually measured in either a total number of full cycles or in years. Over time,
              it will lose some of its capacity as well. A battery’s lifespan is generally somewhere from five to 15
              years, although it is expected to increase significantly to keep up with the growth of solar panels
              through the years.
            </Typography>
          </div>
        </Grid>
        <Grid item xs={12} md={4} style={{ padding: "2rem" }}>
          <div className={classes.staticCard}>
            <Typography variant="body1" component="p" style={{ textAlign: "center" }}>
              <strong>CAPACITY AND POWER</strong>
            </Typography>
            <br />
            <Typography variant="body1" component="p">
              A battery’s capacity is the total amount of electricity it can store measured in kilowatt-hours (kWh). The
              battery’s power rating will tell you the amount of electricity that the battery can deliver at one time
              measured in kilowatts (kW). A battery with high capacity but low power will be able to supply power to a
              number of key appliances in your home for a long time. A battery with low capacity but high power will be
              able to power your entire home for a short amount of time. Multiple batteries of different capacities can
              also be stacked to get a larger net capacity.
            </Typography>
          </div>
        </Grid>
        <Grid item xs={12} md={4} style={{ padding: "2rem" }}>
          <div className={classes.staticCard}>
            <Typography variant="body1" component="p" style={{ textAlign: "center" }}>
              <strong>DEPTH OF DISCHARGE</strong>
            </Typography>
            <br />
            <Typography variant="body1" component="p">
              The DoD measures the degree to which a battery can be used relative to its total capacity. If a battery
              has a 100% DoD it means you can use the full battery storage amount (e.g. 2.5kWh) to power your home. If a
              battery has a 94% DoD, it means you can use up to 94% of the battery capacity (e.g. for a 2.5kWh battery,
              you can use down to 2.35kWh before the battery needs to charge again).
            </Typography>
          </div>
        </Grid>
      </Grid>
      {/* types */}
      <Grid item container xs={12}>
        <Grid item xs={12}>
          <Typography variant="h6" component="p" color="secondary" style={{ textAlign: "center" }}>
            <strong>THE 2 MAJOR TYPES OF SOLAR BATTERIES ARE GIVEN BELOW:</strong>
          </Typography>
        </Grid>
        <Grid item xs={12} md={6} style={{ padding: matches ? "3rem 4rem" : "1.5rem" }}>
          <div className={classes.card}>
            <div style={{ textAlign: "center" }}>
              <Typography variant="h6" component="p" style={{ textAlign: "center" }}>
                <strong>LITHIUM ION BATTEERY</strong>
              </Typography>
              <br />
              <div style={{ maxWidth: "300px", margin: "0 auto" }}>
                <img src={batteryType1} style={{ display: "flex", width: "100%" }} alt="Lithium Ion Battery" />
              </div>
              <Collapse in={expanded.lithiumIonBattery} timeout="auto" unmountOnExit>
                <div>
                  <br />
                  <Typography variant="body1" component="p">
                    They are the most popular of home storage batteries. Lithium-ion batteries have the longest lifespan
                    and higher DoD and are very compact and light compared to the other battery types. With all these
                    benefits, however, they are the most expensive. Lithium ion batteries are so called because they
                    work by moving lithium ions through an electrolyte inside of the battery. One can charge and
                    discharge lithium ion batteries hundreds or even thousands of times. Lithium ion batteries used in
                    home energy storage systems combine multiple lithium ion battery cells with power electronics devics
                    that control the performance and safety of the whole battery system.
                  </Typography>
                </div>
              </Collapse>
            </div>
          </div>
          <div className={classes.cardButton}>
            <IconButton
              className={clsx(classes.expand, {
                [classes.expandOpen]: expanded.lithiumIonBattery,
              })}
              onClick={() => handleExpandClick("part1")}
              aria-expanded={expanded.lithiumIonBattery}
              aria-label="show more"
              style={{ padding: "0px" }}
            >
              <ExpandMoreIcon style={{ fontSize: "28px" }} />
            </IconButton>
          </div>
        </Grid>
        <Grid item xs={12} md={6} style={{ padding: matches ? "3rem 4rem" : "1.5rem" }}>
          <div className={classes.card}>
            <div style={{ textAlign: "center" }}>
              <Typography variant="h6" component="p" style={{ textAlign: "center" }}>
                <strong>LEAD ACID BATTERY</strong>
              </Typography>
              <br />
              <div style={{ maxWidth: "300px", margin: "0 auto" }}>
                <img src={batteryType2} style={{ display: "flex", width: "100%" }} alt="Lead Acid Battery" />
              </div>
              <Collapse in={expanded.leadAcidBattery} timeout="auto" unmountOnExit>
                <div>
                  <br />
                  <Typography variant="body1" component="p">
                    A lead acid battery is a kind of rechargeable battery that stores electrical energy by using
                    chemical reactions between lead, water, and sulfuric acid. These batteries have the shortest
                    lifespan and capacity. These are a good option if you are trying to store energy on a budget, but
                    will cost you more in the long run as you have to replace them more frequently. Lead acid batteries
                    have been used for decades and are one of the cheapest varieties in home energy storage for off-grid
                    power systems. The downfall to buying this type of technology is that it is becoming outdated and
                    has a lower DoD compared to other battery types.
                  </Typography>
                </div>
              </Collapse>
            </div>
          </div>
          <div className={classes.cardButton}>
            <IconButton
              className={clsx(classes.expand, {
                [classes.expandOpen]: expanded.leadAcidBattery,
              })}
              onClick={() => handleExpandClick("part2")}
              aria-expanded={expanded.leadAcidBattery}
              aria-label="show more"
              style={{ padding: "0px" }}
            >
              <ExpandMoreIcon style={{ fontSize: "28px" }} />
            </IconButton>
          </div>
        </Grid>
      </Grid>
      {/* warranty */}
      <Grid item container xs={12} style={{ marginTop: "4rem" }}>
        <Grid item xs={12} md={6}>
          <div style={{ position: "relative", display: "flex", justifyContent: "center", alignItems: "center" }}>
            <div className={classes.blueStrikeLine}></div>
            <img
              src={warranty}
              style={{ display: "flex", width: "150px", height: "150px", zIndex: 10 }}
              alt="Warranty"
            />
          </div>
          <div className={classes.content}>
            <Typography variant="h5" color="secondary" style={{ textAlign: "center" }}>
              <strong>WARRANTY OF SOLAR BATTERIES</strong>
            </Typography>
            <br />
            <Typography variant={matches ? "h6" : "body1"} component="p" color="secondary">
              Solar batteries have an average equipment warranty of 5 years provided by the company. However some
              companies offer the possibility of extending the warranty upto 10 years.
            </Typography>
          </div>
        </Grid>
        <Grid item xs={12} md={6}>
          <div style={{ position: "relative", display: "flex", justifyContent: "center", alignItems: "center" }}>
            <div className={classes.blueStrikeLine}></div>
            <img
              src={availability}
              style={{ display: "flex", width: "150px", height: "150px", zIndex: 10 }}
              alt="Availability"
            />
          </div>
          <div className={classes.content}>
            <Typography variant="h5" color="secondary" style={{ textAlign: "center" }}>
              <strong>SOLAR BATTERY BRANDS AVAILABILITY</strong>
            </Typography>
            <br />
            <Typography variant={matches ? "h6" : "body1"} component="p" color="secondary">
              You can purchase solar batteries directly through our company website “SOLRUF”. The link for purchasing
              solar batteries is given below:
            </Typography>
            <br />
            <Link
              style={{ color: "#bfbfbf", display: "flex", alignItems: "center" }}
              href="https://solruf.com/products/"
              rel="noopener noreferrer"
              target="_blank"
            >
              <Typography variant="body1" component="p" style={{ color: "#b3b3b3" }}>
                https://solruf.com/products/
              </Typography>
              &nbsp;
              <OpenInNewIcon style={{ color: "#4d4d4d" }} />
            </Link>
            <br />
            <Typography variant="h5" color="secondary">
              We have the following brands available
            </Typography>
            <br />
            <div style={{ width: "100%" }}>
              <img src={batteryCompanies} style={{ width: "100%", height: "300px" }} alt="Brands" />
            </div>
          </div>
        </Grid>
      </Grid>
      {/* end */}
    </Grid>
  );
};

export default SolarBatteries;
